name: baremetal-ci-actions
run-name: ${{ github.actor }} running Baremetal CI actions
on: [push]

env:
  platform_setup: "fsw-gds"
  baremetal_bin: ${{ github.workspace }}/build-artifacts/teensy41/BaremetalReference/bin/BaremetalReference.hex
  upload_addr: usb:3120000
  gds_args: --comm-adapter uart --uart-device /dev/tty.usbmodem159910601
  dict_path: ${{ github.workspace }}/build-artifacts/teensy41/BaremetalReference/dict/BaremetalReferenceTopologyAppDictionary.xml
  test_path: BaremetalReference/test/int/baremetal_ref_integration_test.py
  workspace_path: ${{ github.workspace }}

jobs:

  build:
    runs-on: self-hosted
    outputs:
      platform_setup: ${{ env.platform_setup }}
      start_cmd: arduino-cli upload --fqbn teensy:avr:teensy41 -p ${{ env.upload_addr }} -i ${{ env.baremetal_bin }}
      gds_args: ${{ env.gds_args }}
      dict_path: ${{ env.dict_path }}
      test_path: ${{ env.test_path }}
      workspace_path: ${{ env.workspace_path }}
    steps:
      - uses: actions/checkout@v4
      - name: "Checkout F' Repository"
        uses: actions/checkout@v4
        with:
          submodules: true
          path: ${{ inputs.fprime_location }}
      - name: "Build"
        run: |
             python3 -m venv ./fprime-venv
             . ./fprime-venv/bin/activate
             pip3 install -r ${{ inputs.fprime_location }}./fprime/requirements.txt
             curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=. sh
             git clone https://github.com/SterlingPeet/arduino-cli-cmake-wrapper.git
             cd arduino-cli-cmake-wrapper
             git checkout update/refactor
             pip install .
             cd ..
             fprime-util generate
             fprime-util build
      - name: "Temp step, file renaming"
        run: |
             mv ${{ github.workspace }}/lib/arduino/fprime-arduino/ATmega/vendor/libraries/TimerOne/examples/FanSpeed/FanSpeed.pde ${{ github.workspace }}/lib/arduino/fprime-arduino/ATmega/vendor/libraries/TimerOne/examples/FanSpeed/FanSpeed.ino
             mv ${{ github.workspace }}/lib/arduino/fprime-arduino/ATmega/vendor/libraries/TimerOne/examples/Interrupt/Interrupt.pde ${{ github.workspace }}/lib/arduino/fprime-arduino/ATmega/vendor/libraries/TimerOne/examples/Interrupt/Interrupt.ino
      - run: echo "Expose env vars for reusable workflow."

  fit:
    needs: build
    uses: ./.github/workflows/reusable_fit_ci.yml
    with:
      runs_on: self-hosted
      platform_setup: ${{ needs.build.outputs.platform_setup }}
      start_cmd: ${{ needs.build.outputs.start_cmd }}
      gds_args: ${{ needs.build.outputs.gds_args }}
      dict_path: ${{ needs.build.outputs.dict_path }}
      test_path: ${{ needs.build.outputs.test_path }}
      workspace_path: ${{ needs.build.outputs.workspace_path }}
