name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  baremetal:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: "Checkout F' Repository"
        uses: actions/checkout@v4
        with:
          submodules: true
          path: ${{ inputs.fprime_location }}
      - uses: ./fprime/.github/actions/setup
      - name: "Install requirements.txt"
        run: pip3 install -r ${{ inputs.fprime_location }}./fprime/requirements.txt
        shell: bash
      - name: "Generate build cache"
      working-direcotry: ${{ inputs.build_location}}
      run: |
        fprime-util generate  ${{ runner.debug == '1' && '--verbose' || '' }} ${{ inputs.target_platform }}
      shell: bash
