name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  baremetal-int:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: "Checkout F' Repository"
        uses: actions/checkout@v4
        with:
          submodules: true
          path: ${{ inputs.fprime_location }}
      - name: "Build"
        run: |
             python3 -m venv ./fprime-venv
             . ./fprime-venv/bin/activate
             pip3 install -r ${{ inputs.fprime_location }}./fprime/requirements.txt
             curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=. sh
             git clone https://github.com/SterlingPeet/arduino-cli-cmake-wrapper.git
             cd arduino-cli-cmake-wrapper
             git checkout update/refactor
             pip install .
             cd ..
             fprime-util generate
             fprime-util build
        shell: bash
      - name: "Temp step, file renaming"
        run: |
             mv ${{ github.workspace }}/lib/arduino/fprime-arduino/ATmega/vendor/libraries/TimerOne/examples/FanSpeed/FanSpeed.pde ${{ github.workspace }}/lib/arduino/fprime-arduino/ATmega/vendor/libraries/TimerOne/examples/FanSpeed/FanSpeed.ino
             mv ${{ github.workspace }}/lib/arduino/fprime-arduino/ATmega/vendor/libraries/TimerOne/examples/Interrupt/Interrupt.pde ${{ github.workspace }}/lib/arduino/fprime-arduino/ATmega/vendor/libraries/TimerOne/examples/Interrupt/Interrupt.ino
        shell: bash
      - name: "Burn"
        run: |
             arduino-cli upload --fqbn teensy:avr:teensy41 -p usb:3120000 -i ${{ github.workspace }}/build-artifacts/teensy41/BaremetalReference/bin/BaremetalReference.hex
        shell: bash
      - name: "Start GDS"
        run: fprime-gds -n --dictionary ./build-artifacts/teensy41/BaremetalReference/dict/BaremetalReferenceTopologyAppDictionary.xml --comm-adapter uart --uart-device /dev/tty.usbmodem159910601 &
        shell: bash
