name: resuable-fit

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"
      log_path:
        required: true
        type: string
      non_embedded:
        required: true
        type: boolean
      # following are labelled as not required but are needed if non_embedded is false
      fsw_first:
        required: false
        type: boolean
        default: true
      start_cmd:
        required: false
        type: string
        default: "fprime-gds"
      gds_args:
        required: false
        type: string
      dict_path:
        required: false
        type: string
      test_path:
        required: false
        type: string

jobs:
# Following 3 jobs are on a switch, only one will run based on 2 conditionals: non_embedded and fsw_first.
# job 1 start fsw gds together: if non_embedded is true.
# job 2 start fsw first and then gds: if not non_embedded and fsw_first is true
# job 3 start gds and then fsw: if not non_embedded and not fsw_first
# after one of these 3 jobs run, fit job will run.
#
#           /    non-embedded   \
# build --->|    fsw-gds        |---> fit
#           \    gds-fsw        /

  non-embedded:
    if: ${{ inputs.non_embedded }}
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: "Start FSW and GDS"
        run: ${{ inputs.start_cmd }}
      - name: "Run Integration tests"
        run: |
            pytest ${{ inputs.test_path }} --dictionary ${{ inputs.dict_path }} -rP | tee ${{ inputs.log_path }}

  fsw-gds:
    if: ${{ !inputs.non_embedded && inputs.fsw_first }}
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: "Start FSW"
        run: ${{ inputs.start_cmd }}
      - name: "Start GDS"
        run: |
            fprime-gds -n --dictionary ${{ inputs.dict_path }} --gui none ${{ inputs.gds_args }} &
            sleep 10
      - name: "Run Integration tests"
        run: |
            pytest ${{ inputs.test_path }} --dictionary ${{ inputs.dict_path }} -rP | tee ${{ inputs.log_path }}

  gds-fsw:
    if: ${{ !inputs.non_embedded && !inputs.fsw_first }}
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: "Start GDS"
        run: fprime-gds -n --dictionary ${{ inputs.dict_path }} --gui none ${{ inputs.gds_args }} &
      - name: "Start FSW"
        run: |
            ${{ inputs.start_cmd }}
            sleep 10
      - name: "Run Integration tests"
        run: |
            pytest ${{ inputs.test_path }} --dictionary ${{ inputs.dict_path }} -rP | tee ${{ inputs.log_path }}
