name: resuable-fit

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"
      platform_setup:
        required: true
        type: string
        default: "non-embedded"
      start_cmd:
        required: false
        type: string
        default: "fprime-gds"
      gds_args:
        required: false
        type: string
      dict_path:
        required: false
        type: string
      test_path:
        required: false
        type: string
      workspace_path:
        required: true
        type: string

jobs:
# Following jobs are on a switch, only one will run based on platform_setup string.
# Each job has a different method of starting FSW, FIT is run at the end of each job.
# If adding a new setup make sure it does not collide with an existing job.
# After one of these jobs is run, the upload FIT artifact job will then run.
#
#           /    non-embedded   \
# build --->|    fsw-gds        |---> upload-fit-artifacts
#           \    gds-fsw        /

  non-embedded:
    if: ${{ inputs.platform_setup == 'non-embedded' }}
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: "Start FSW and GDS"
        run: |
            . ./fprime-venv/bin/activate
            ${{ inputs.start_cmd }}
      - name: "Run Integration tests"
        run: |
            . ./fprime-venv/bin/activate
            sleep 12
            pytest ${{ inputs.test_path }} --dictionary ${{ inputs.dict_path }} -rP

  fsw-gds:
    if: ${{ inputs.platform_setup == 'fsw-gds' }}
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: "Start FSW"
        run: ${{ inputs.start_cmd }}
      - name: "Start GDS"
        run: |
            . ./fprime-venv/bin/activate
            fprime-gds -n --dictionary ${{ inputs.dict_path }} --gui none ${{ inputs.gds_args }} &
            sleep 12
      - name: "Run Integration tests"
        run: |
            . ./fprime-venv/bin/activate
            pytest ${{ inputs.test_path }} -rP --dictionary ${{ inputs.dict_path }} --logs ./

  gds-fsw:
    if: ${{ inputs.platform_setup == 'gds-fsw' }}
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: "Start GDS"
        run: |
            . ./fprime-venv/bin/activate
            fprime-gds -n --dictionary ${{ inputs.dict_path }} --gui none ${{ inputs.gds_args }} &
      - name: "Start FSW"
        run: |
            ${{ inputs.start_cmd }}
            sleep 12
      - name: "Run Integration tests"
        run: |
            . ./fprime-venv/bin/activate
            pytest ${{ inputs.test_path }} --dictionary ${{ inputs.dict_path }} -rP

  upload-fit-artifact:
    runs-on: ${{ inputs.runs_on }}
    if: ${{ always() }} #as long as one of the above jobs run, this job will run
    needs: [non-embedded, fsw-gds, gds-fsw]
    steps:
      - name: "Upload Integration Test Results"
        #Navigate to workspace path. nagigate into newest directory, which is for test logs.
        #Rename test log because it contains date time and time is separated by colons that upload-artifact cannot handle.
        #Store full path to test log xlsx in a variable for upload-artifact to use.
        run: |
            cd ${{ inputs.workspace_path }}
            cd "$(ls -td -- */ | head -n 1)"
            mv TestLog*.xlsx TestLog.xlsx
            echo "TEST_LOG_PATH=$(realpath -s *.xlsx)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: TestLog
          path: ${{ env.TEST_LOG_PATH }}
