name: temp-ci-actions
run-name: ${{ github.actor }} running Baremetal CI actions
#on: [push]

env:
  platform_setup: 'gds-fsw'
  baremetal_bin: ${{ github.workspace }}/build-artifacts/teensy41/BaremetalReference/bin/BaremetalReference.hex
  upload_addr: usb:3120000
  gds_args: --comm-adapter uart --uart-device /dev/tty.usbmodem159910601
  dict_path: ${{ github.workspace }}/build-artifacts/teensy41/BaremetalReference/dict/BaremetalReferenceTopologyAppDictionary.xml
  test_path: BaremetalReference/test/int/baremetal_ref_integration_test.py

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      platform_setup: ${{ env.platform_setup }}
      start_cmd: arduino-cli upload --fqbn teensy:avr:teensy41 -p ${{ env.upload_addr }} -i ${{ env.baremetal_bin }}
      gds_args: ${{ env.gds_args }}
      dict_path: ${{ env.dict_path }}
      test_path: ${{ env.test_path }}
    steps:
      - uses: actions/checkout@v4
      - name: "Checkout F' Repository"
        uses: actions/checkout@v4
        with:
          submodules: true
          path: ${{ inputs.fprime_location }}
      - name: "Build"
        run: echo ${{ github.workspace }}
      - run: echo "Expose env vars for reusable workflow."

  fit:
    needs: build
    uses: ./.github/workflows/reusable_fit.yml
    with:
      runs_on: ubuntu-latest
      platform_setup: ${{ needs.build.outputs.platform_setup }}
      start_cmd: ${{ needs.vars.outputs.start_cmd }}
      gds_args: ${{ needs.vars.outputs.gds_args }}
      dict_path: ${{ needs.vars.outputs.dict_path }}
      test_path: ${{ needs.vars.outputs.test_path }}
